### ISSUE TITLE
Fix EML in dwca-export for molecular data

### ISSUE THREAD

**Issue by mskyttner** [bioatlas/data-mobilization-pipeline#3]
The metadata is not working, needs to be fixed, probably not well-formed?

**Comment by pragermh** [comment]
New eml now in [indata-dynprop](https://github.com/bioatlas/data-mobilization-pipeline/tree/master/molecular-data/using-existing-taxa/indata-dynprop).

**Comment by mskyttner** [comment]
Thanks @pragermh, @shahmanash can you reload this at beta.bioatlas.se and get back with results?
